<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Skill\Skilltree;
use App\Models\Skill\SkilltreeText;
use Faker\Generator as Faker;

$factory->define(SkilltreeText::class, static function (Faker $faker) {
    $name = $faker->randomElement([
        'Poison Resistance',
        'Paralysis Resistance',
        'Sleep Resistance',
        'Stun Resistance',
        'Muck Resistance',
        'Blast Resistance',
        'Bleeding Resistance',
        'Iron Skin',
        'Earplugs',
        'Windproof',
        'Tremor Resistance',
        'Dungmaster',
        'Effluvial Expert',
        'Heat Guard',
        'Attack Boost',
        'Defense Boost',
        'Health Boost',
        'Recovery Up',
        'Recovery Speed',
        'Fire Resistance',
        'Water Resistance',
        'Ice Resistance',
        'Thunder Resistance',
        'Dragon Resistance',
        'Blight Resistance',
        'Fire Attack',
        'Water Attack',
        'Ice Attack',
        'Thunder Attack',
        'Dragon Attack',
        'Poison Attack',
        'Paralysis Attack',
        'Sleep Attack',
        'Blast Attack',
        'Normal Shots',
        'Piercing Shots',
        'Spread/Power Shots',
        'Free Elem/Ammo Up',
        'Critical Eye',
        'Critical Boost',
        'Weakness Exploit',
        'Focus',
        'Power Prolonger',
        'Handicraft',
        'Critical Draw',
        'Partbreaker',
        'Slugger',
        'Stamina Thief',
        'Master Mounter',
        'Airborne',
        'Latent Power',
        'Agitator',
        'Peak Performance',
        'Heroics',
        'Fortify',
        'Resentment',
        'Resuscitate',
        'Horn Maestro',
        'Capacity Boost',
        'Special Ammo Boost',
        'Artillery',
        'Heavy Artillery',
        'Marathon Runner',
        'Constitution',
        'Leap of Faith',
        'Stamina Surge',
        'Hunger Resistance',
        'Evade Window',
        'Evade Extender',
        'Guard',
        'Quick Sheath',
        'Wide-Range',
        'Item Prolonger',
        'Free Meal',
        'Speed Eating',
        'Speed Sharpening',
        'Bombardier',
        'Mushroomancer',
        'Master Fisher',
        'Pro Transporter',
        'Master Gatherer',
        'Honey Hunter',
        'Carving Pro',
        'Divine Blessing',
        'Palico Rally',
        'Botanist',
        'Geologist',
        'Maximum Might',
        'Slinger Capacity',
        'Stealth',
        'Flinch Free',
        'Scoutfly Range Up',
        'Speed Crawler',
        'Jump Master',
        'Survival Expert',
        'Aquatic/Polar Mobility',
        'Cliffhanger',
        'Blindsider',
        'Scholar',
        'Entomologist',
        'Effluvia Resistance',
        'Scenthound',
        'Forager\'s Luck',
        'Detector',
        'Tool Specialist',
        'Affinity Sliding',
        'Intimidator',
        'Hasten Recovery',
        'Super Recovery',
        'Poison Duration Up',
        'Adrenaline',
        'Stamina Cap Up',
        'Critical Element',
        'Mind\'s Eye/Ballistics',
        'Bludgeoner',
        'Non-elemental Boost',
        'Capture Master',
        'Guard Up',
        'Guts',
        'Master\'s Touch',
        'Nullify Wind Pressure',
        'Razor Sharp/Spare Shot',
        'Critical Status',
        'Great Luck',
        'Carving Master',
        'Good Luck',
        'Bow Charge Plus',
        'Punishing Draw',
        'Protective Polish',
        'BBQ Master',
        'Blast Functionality',
        'Elderseal Boost',
        'Para Functionality',
        'Poison Functionality',
        'Sleep Functionality',
        'Elemental Airborne',
        'True Razor Sharp/Spare Shot',
        'Offensive Guard',
        'Coalescence',
        'Frostcraft',
        'Element Acceleration',
        'True Element Acceleration',
        'Gaia\'s Veil',
        'True Gaia\'s Veil',
        'Dragonvein Awakening',
        'True Dragonvein Awakening',
        'Free Meal Secret',
        'Maximum Might Secret',
        'Bombardier Secret',
        'Slugger Secret',
        'Agitator Secret',
        'Artillery Secret',
        'Stamina Thief Secret',
        'Tool Specialist Secret',
        'Latent Power Secret',
        'Divine Blessing Secret',
        'Slinger Ammo Secret',
        'Heroics Secret',
        'True Critical Status',
        'True Critical Element',
        'Joy\'s Gift',
        'Joy\'s Gratitude',
        'Gratitude\'s Gift',
        'Gratitude\'s Blessing',
        'Full Bloom\'s Gift',
        'Full Bloom Gratitude',
    ]);

    return [
        'id' => static function () {
            return factory(Skilltree::class)->create()->id;
        },
		'lang_id' => $faker->languageCode,
		'name' => $name,
		'description' => $faker->text(),
    ];
});
